# Generated by Django 5.1.7 on 2026-01-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PAGE_VIEW', 'Page View'), ('ACTION', 'Action')], max_length=20)),
                ('action', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='activity_us_created_7fb544_idx'), models.Index(fields=['user', 'created_at'], name='activity_us_user_id_a5138e_idx'), models.Index(fields=['event_type', 'created_at'], name='activity_us_event_t_d7103c_idx')],
            },
        ),
    ]
