# Generated by Django 5.1.7 on 2026-01-23 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='device',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='referrer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='request_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='session_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', 'created_at'], name='activity_us_action_8f9328_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='activity_us_ip_addr_540208_idx'),
        ),
    ]
