# Generated by Django 5.1.7 on 2026-01-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_useractivitylog_city_useractivitylog_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
